name: CI

on:
  push:

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run ESLint
      run: npm run lint
      
    - name: TypeScript check - API
      run: |
        cd apps/api
        npx tsc --noEmit
        
    - name: TypeScript check - Mobile
      run: |
        cd apps/mobile
        npx tsc --noEmit
        
    - name: TypeScript check - Shared
      run: |
        cd packages/shared
        npx tsc --noEmit

  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test

  docker-compose-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and test docker-compose
      run: |
        export DOCKER_BUILDKIT=1
        export COMPOSE_DOCKER_CLI_BUILD=1
        docker-compose build
      
    - name: Start services
      run: docker-compose up -d
      
    - name: Wait for services
      run: sleep 10
      
    - name: Check API health
      run: |
        curl -f http://localhost:3000/health || exit 1
        
    - name: Stop services
      run: docker-compose down